
export const CartAction = {
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    UPDATE_CART_ITEM_QUANTITY: 'UPDATE_CART_ITEM_QUANTITY',
    SET_CART_ITEMS: 'SET_CART_ITEMS',
    CLEAR_CART: 'CLEAR_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART'
};

export const WishlistAction = {
    ADD_PRODUCT_TO_WISHLIST: 'ADD_PRODUCT_TO_WISHLIST',
    SET_WISHLIST_ITEMS: 'SET_WISHLIST_ITEMS',
    CLEAR_WISHLIST: 'CLEAR_WISHLIST',
    REMOVE_FROM_WISHLIST: 'REMOVE_FROM_WISHLIST'
};